import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap-icons/font/bootstrap-icons.css"
import Nav from '../components/Nav';
import { cookies } from 'next/headers';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const token = cookies().get('token');
  return (
    <html lang="en">
      <body className="min-h-screen">
        <div className='flex justify-center items-center p-24'>
          {children}
        </div>
      </body>
    </html>
  )
}